# -*- coding: utf-8 -*-
"""Xgbfile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KgF_q_Pis783-Wh_18hb6aRG7etxu06y
"""

import pandas as pd
import streamlit as st
import pickle

st.title("📈 Demand Forecasting System")
st.sidebar.header("User Input Parameters")

model = pickle.load(open('demand_model.pkl', 'rb'))

def user_input_features():

    Store = st.sidebar.number_input('Store', min_value=1, value=1)

    IsHoliday = st.sidebar.selectbox(
        'Is Holiday',
        [0, 1]
    )

    Dept = st.sidebar.number_input(
        'Department',
        min_value=1,
        value=1
    )

    Temperature = st.sidebar.number_input(
        'Temperature',
        value=50.0
    )

    Fuel_Price = st.sidebar.number_input(
        'Fuel Price',
        value=3.0
    )

    MarkDown1 = st.sidebar.number_input(
        'MarkDown1',
        value=0.0
    )

    MarkDown2 = st.sidebar.number_input(
        'MarkDown2',
        value=0.0
    )

    MarkDown3 = st.sidebar.number_input(
        'MarkDown3',
        value=0.0
    )

    MarkDown4 = st.sidebar.number_input(
        'MarkDown4',
        value=0.0
    )

    MarkDown5 = st.sidebar.number_input(
        'MarkDown5',
        value=0.0
    )

    CPI = st.sidebar.number_input(
        'CPI',
        value=200.0
    )

    Unemployment = st.sidebar.number_input(
        'Unemployment',
        value=7.5
    )

    Type = st.sidebar.selectbox(
        'Store Type',
        [1, 2, 3]
    )

    Size = st.sidebar.number_input(
        'Store Size',
        value=150000
    )

    data = {
        'Store': Store,
        'IsHoliday': IsHoliday,
        'Dept': Dept,
        'Temperature': Temperature,
        'Fuel_Price': Fuel_Price,
        'MarkDown1': MarkDown1,
        'MarkDown2': MarkDown2,
        'MarkDown3': MarkDown3,
        'MarkDown4': MarkDown4,
        'MarkDown5': MarkDown5,
        'CPI': CPI,
        'Unemployment': Unemployment,
        'Type': Type,
        'Size': Size
    }

    features = pd.DataFrame(
        data,
        index=[0]
    )

    return features


df = user_input_features()
Date = st.date_input("Date")

df["Year"] = Date.year
df["Month"] = Date.month
df["Day"] = Date.day
df["Unnamed: 0"] = 0

st.subheader("User Input Parameters")
st.write(df)

expected_cols = [
    'Unnamed: 0', 'Store', 'IsHoliday', 'Dept', 'Temperature',
    'Fuel_Price', 'MarkDown1', 'MarkDown2', 'MarkDown3',
    'MarkDown4', 'MarkDown5', 'CPI', 'Unemployment',
    'Type', 'Size', 'Year', 'Month', 'Day'
]

df = df[expected_cols]

prediction = model.predict(df)

st.subheader("Predicted Weekly Sales")

st.success(
    f"${prediction[0]:,.2f}"
)